### ISSUE TITLE
automatic cloudprofile management

### ISSUE THREAD

**Issue by JensAc** [gardener-community/cloudprofiles#2]
Each cloudprofile is a 5-tuple consisting of the supported:

1. k8s-versions
2. machine-types (flavors)
3. volume-types
4. os-images
5. regions

### 1. K8s-versions
The upstream versions can be found here: https://github.com/kubernetes/kubernetes/releases

Restrictions to these versions come from:

a) The gardener version
b) extensions (provider, os, network)?
c) OS-image?

### 2. Machine-types
The list of available machine-types is cloud-specific. Maybe steampipe (https://steampipe.io/docs) can be a helper to acquire information in a uniform way.

Restrictions:
some machine types may not be available in some zones of some regions

### 3. volume-types
The list of available volume-types is cloud-specific. Maybe steampipe (https://steampipe.io/docs) can be a helper to acquire information in a uniform way.

### 4. os-images
The list of available os-images is cloud-specific. Maybe steampipe (https://steampipe.io/docs) can be a helper to acquire information in a uniform way.

Restrictions:

* only images with an according os-extension (as of now ubuntu, coreos, suse-chost and gardenlinux) are of interest

### 5. regions
The list of available regions is cloud-specific. Maybe steampipe (https://steampipe.io/docs) can be a helper to acquire information in a uniform way.

**Comment by berendt** [comment]
Check if it is possible to automate the update of e.g. image version with Renovate.

**Comment by j2L4e** [comment]
Some steampipe fiddling with hcloud plugin:

```sql
with dc as (select l.name                                               as location,
                   l.network_zone                                       as zone,
                   dc.name                                              as datacenter,
                   jsonb_array_elements(dc.server_types_available)::int as server_type_id
            from hcloud_datacenter dc
                     join hcloud_location l on dc.location_id = l.id)

select st.description, st.cores, st.disk, st.memory, zone, location, datacenter
from dc
         join hcloud_server_type st on st.id = dc.server_type_id
where cpu_type = 'shared'
  and zone = 'eu-central';
```

```
+-----------+-----+----+------+----------+--------+----------+
|description|cores|disk|memory|zone      |location|datacenter|
+-----------+-----+----+------+----------+--------+----------+
|CX11       |1    |20  |2     |eu-central|nbg1    |nbg1-dc3  |
|CX11       |1    |20  |2     |eu-central|fsn1    |fsn1-dc14 |
|CX11       |1    |20  |2     |eu-central|hel1    |hel1-dc2  |
|CX21       |2    |40  |4     |eu-central|hel1    |hel1-dc2  |
|CX21       |2    |40  |4     |eu-central|fsn1    |fsn1-dc14 |
|CX21       |2    |40  |4     |eu-central|nbg1    |nbg1-dc3  |
|CX31       |2    |80  |8     |eu-central|nbg1    |nbg1-dc3  |
|CX31       |2    |80  |8     |eu-central|fsn1    |fsn1-dc14 |
|CX31       |2    |80  |8     |eu-central|hel1    |hel1-dc2  |
|CX41       |4    |160 |16    |eu-central|hel1    |hel1-dc2  |
|CX41       |4    |160 |16    |eu-central|nbg1    |nbg1-dc3  |
|CX41       |4    |160 |16    |eu-central|fsn1    |fsn1-dc14 |
|CX51       |8    |240 |32    |eu-central|fsn1    |fsn1-dc14 |
|CX51       |8    |240 |32    |eu-central|nbg1    |nbg1-dc3  |
|CX51       |8    |240 |32    |eu-central|hel1    |hel1-dc2  |
|CPX 11     |2    |40  |2     |eu-central|hel1    |hel1-dc2  |
|CPX 11     |2    |40  |2     |eu-central|fsn1    |fsn1-dc14 |
|CPX 11     |2    |40  |2     |eu-central|nbg1    |nbg1-dc3  |
|CPX 21     |3    |80  |4     |eu-central|fsn1    |fsn1-dc14 |
|CPX 21     |3    |80  |4     |eu-central|hel1    |hel1-dc2  |
|CPX 21     |3    |80  |4     |eu-central|nbg1    |nbg1-dc3  |
|CPX 31     |4    |160 |8     |eu-central|hel1    |hel1-dc2  |
|CPX 31     |4    |160 |8     |eu-central|nbg1    |nbg1-dc3  |
|CPX 31     |4    |160 |8     |eu-central|fsn1    |fsn1-dc14 |
|CPX 41     |8    |240 |16    |eu-central|fsn1    |fsn1-dc14 |
|CPX 41     |8    |240 |16    |eu-central|nbg1    |nbg1-dc3  |
|CPX 41     |8    |240 |16    |eu-central|hel1    |hel1-dc2  |
|CPX 51     |16   |360 |32    |eu-central|fsn1    |fsn1-dc14 |
|CPX 51     |16   |360 |32    |eu-central|hel1    |hel1-dc2  |
+-----------+-----+----+------+----------+--------+----------+
```

**Comment by lotharbach** [comment]
Wishes from devboard to complete this card: 
- [x] automatic updates/PRs for k8s versions (independent of cloud, track github/kubernetes)
- [ ] automatic updates/PRs for os-version
    * gardenlinux specifies new image IDs in release notes, track github/gardenlinux. For openstacks this also requires the CSP to upload them
    * for clouds with ubuntu, probably cloud provider creates updated images and needs cloud specific logic
  * flavors, volume types, regions are fine to be updated manually, with cloud specific helper scripts. Helper scripts should come with some documentation of their ability and what to do with the output.
